# Numpy operations

**Arithmetic Operations**

In [16]:
import numpy as np 

arr1 = np.arange(4, dtype = np.float_).reshape(2, 2) 
 
print('First array:') 
print(arr1)
 
print('\nSecond array:') 
arr2 = np.array([12, 12]) 
print(arr2)
 
print('\nAdding the two arrays:') 
print(np.add(arr1, arr2))
 
print('\nSubtracting the two arrays:') 
print(np.subtract(arr1, arr2))
 
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))
 
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))

First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


**numpy.reciprocal()**

In [17]:
import numpy as np 
arr = np.array([25, 1.33, 1, 1, 100]) 
 
print('Our array is:')
print(arr)
 
print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr))
 
arr2 = np.array([25], dtype = int)
print('\nThe second array is:')
print(arr2)
 
print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr2))

Our array is:
[ 25.     1.33   1.     1.   100.  ]

After applying reciprocal function:
[0.04      0.7518797 1.        1.        0.01     ]

The second array is:
[25]

After applying reciprocal function:
[0]


**numpy.power()**

In [19]:
import numpy as np 
 
 
arr = np.array([5, 10, 15]) 
 
print('First array is:') 
print(arr)
 
print('\nApplying power function:') 
print(np.power(arr, 2))
 
print('\nSecond array is:') 
arr1 = np.array([1, 2, 3]) 
print(arr1)
 
print('\nApplying power function again:') 
print(np.power(arr, arr1))

First array is:
[ 5 10 15]

Applying power function:
[ 25 100 225]

Second array is:
[1 2 3]

Applying power function again:
[   5  100 3375]


**numpy.mod()**

In [21]:
import numpy as np 
 
 
arr = np.array([5, 15, 20]) 
arr1 = np.array([2, 5, 9]) 
 
print('First array:') 
print(arr) 
 
print('\nSecond array:') 
print(arr1)
 
print('\nApplying mod() function:') 
print(np.mod(arr, arr1))
 
print('\nApplying remainder() function:') 
print(np.remainder(arr, arr1))

First array:
[ 5 15 20]

Second array:
[2 5 9]

Applying mod() function:
[1 0 2]

Applying remainder() function:
[1 0 2]
